// MLBB Draft Assistant — hero meta database
// Blended from live-server Season 41 (Patch 2.1.95a) win/pick/ban rates
// and MPL Indonesia Season 18 pro draft data (most current offline pro season, Aug–Nov 2026).
// tier: S = must ban/pick priority, A = strong contest pick, B = solid situational, C = off-meta/rare
// proBan: true if it shows up as a heavily-contested ban in current MPL drafts
// counters: heroes that answer this pick well (used for counter-suggestions)
// bait: notes on how this hero is used as a bait/trade pick in pro drafts

const HERO_DB = [
  // ===== S TIER — PRIORITY BAN/PICK =====
  { name: "Freya", role: "EXP", type: "Fighter", tier: "S", proBan: true, banRate: 93,
    notes: "The single most contested hero in MPL ID S18 — banned in 93% of games. Flexible dive/skirmish fighter that snowballs any early lead.",
    counters: ["Khufra", "Minotaur", "Atlas"],
    bait: "Almost never survives to pick phase — if it's still open going into Ban Phase 2, treat it as a trap: whoever leaves it up is gifting the other side a free S-tier fighter." },
  { name: "Atlas", role: "Roam", type: "Tank", tier: "S", proBan: true, banRate: 82,
    notes: "Premier engage tank — ultimate drags the whole enemy team into a teamfight. Second most banned hero in pro play.",
    counters: ["Diggie", "Angela", "Lolita"],
    bait: "A common 'sacrifice' hero in Ban Phase 2 — teams will let this go if they've already banned Freya, since giving up one S-tier engage tank is better than two S-tier snowball threats." },
  { name: "Marcel", role: "Jungle", type: "Mage/Assassin", tier: "S", proBan: true, banRate: 80,
    notes: "Highest win rate hero on live servers (59%+). Cooldown-reset kit lets him chain ultimates and delete backline carries.",
    counters: ["Lolita", "Minotaur", "Franco"],
    bait: "High ban priority but occasionally left open late — if you see it slip to Pick Phase 2, it's usually because both priority bans (Freya/Atlas) already used both teams' Ban Phase 1 slots." },
  { name: "Melissa", role: "Gold", type: "Marksman", tier: "S", proBan: true, banRate: 55,
    notes: "Doll-summon marksman with elite peel and burst — dominant late-game teamfight marksman on the current patch.",
    counters: ["Lancelot", "Ling", "Helcurt"],
    bait: "Frequently 'double-open' bait: teams leave her up expecting the opponent to prioritize Freya/Atlas bans first, then snipe her in Pick Phase 1." },
  { name: "Fanny", role: "Jungle", type: "Assassin", tier: "S", proBan: true, banRate: 54,
    notes: "Cable-swing mobility assassin, always a ban-or-first-pick in pro drafts because of the skill ceiling gap she creates.",
    counters: ["Minotaur", "Khufra", "Atlas"],
    bait: "Comfort-pick bait — if you know the enemy mid/jungler is a known Fanny specialist, banning her denies their whole game plan rather than just a hero." },
  { name: "Novaria", role: "Mid", type: "Mage", tier: "S", proBan: true, banRate: 51,
    notes: "Zoning mage with map-wide utility; consistently inside the top-6 pro bans this season.",
    counters: ["Lancelot", "Gusion", "Selena"],
    bait: null },
  { name: "Paquito", role: "EXP", type: "Fighter", tier: "S", proBan: true, banRate: 46,
    notes: "Mandatory ban-or-pick fighter — parry mechanic punishes greedy engages and skirmishes.",
    counters: ["Terizla", "Esmeralda", "Franco"],
    bait: "Good 'safety valve' pick — if Freya/Atlas/Marcel are all gone, Paquito is the next-best value pick most teams settle for, so watch for him sliding into Pick Phase 1." },
  { name: "Belerick", role: "EXP", type: "Tank", tier: "S", proBan: true, banRate: 58,
    notes: "Damage-reflect tank that shreds fighters/marksmen who auto-attack into him. Most-banned hero on live ladder (58%+).",
    counters: ["Mages with burst (Lylia, Valentina)", "Marksmen with true damage (Claude)"],
    bait: null },
  { name: "Hirara", role: "Mid/Gold", type: "Marksman/Support hybrid", tier: "S", proBan: true, banRate: 22,
    notes: "New-patch hybrid pick with a 74%+ pick-or-ban rate in MPL ID S18 — extremely high priority whenever available.",
    counters: ["Burst assassins (Gusion, Helcurt)"],
    bait: null },
  { name: "Rafaela", role: "Roam", type: "Support", tier: "S", proBan: true, banRate: 35,
    notes: "Top win-rate support on live servers (58%+); pick/slow utility swings skirmishes hard.",
    counters: ["Silence heroes (Pharsa, Helcurt)"],
    bait: null },
  { name: "Miya", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 19,
    notes: "Most-picked hero on live ladder — safe, scaling hypercarry pick when lanes are stable.",
    counters: ["Diggie", "Assassins with burst"],
    bait: null },
  { name: "Estes", role: "Roam", type: "Support", tier: "S", proBan: true, banRate: 38,
    notes: "Global sustain support, warps late-game siege compositions.",
    counters: ["Silence/CC-heavy roamers (Khufra, Diggie)"],
    bait: null },
  { name: "Gloo", role: "EXP/Roam", type: "Tank", tier: "S", proBan: true, banRate: 47,
    notes: "Split-based tank, extremely tanky duelist that punishes squishy comps 1v1.",
    counters: ["True damage/percent-HP heroes (Claude, Karrie)"],
    bait: null },
  { name: "Khufra", role: "Roam", type: "Tank", tier: "S", proBan: false, banRate: 10,
    notes: "Best anti-dive/anti-mobility tank in the game — bubble + ult strip movement effects.",
    counters: ["Ranged poke heroes"],
    bait: "If your comp plans a dive/blink core (Lancelot, Ling, Fanny), banning Khufra is usually worth more than a 'strong hero' ban." },
  { name: "Minotaur", role: "Roam", type: "Tank", tier: "S", proBan: false, banRate: 8,
    notes: "AoE stun + team-wide heal ultimate, strong in coordinated 5-man engages.",
    counters: ["Crowd-control chains that interrupt the ult windup"],
    bait: null },
  { name: "Julian", role: "Jungle", type: "Assassin", tier: "S", proBan: false, banRate: 0,
    notes: "Live-ladder S-tier assassin, snowballs jungle fights extremely hard early.",
    counters: ["Tanks with hard CC (Khufra, Franco)"],
    bait: null },
  { name: "Yi Sun-shin", role: "Jungle", type: "Assassin", tier: "S", proBan: false, banRate: 0,
    notes: "Global-range ultimate assassin, dominant pro/ladder pick this patch.",
    counters: ["Minotaur", "Khufra"],
    bait: null },
  { name: "Harley", role: "Mid", type: "Assassin", tier: "S", proBan: false, banRate: 0,
    notes: "Burst mage-assassin, blink reset lets him pick off backline instantly.",
    counters: ["Tanks with silence/CC (Khufra, Franco)"],
    bait: null },
  { name: "Gusion", role: "Mid", type: "Assassin", tier: "S", proBan: false, banRate: 0,
    notes: "High-mechanical-ceiling burst assassin, still S-tier on the current patch.",
    counters: ["Minotaur", "Khufra", "Lolita"],
    bait: null },
  { name: "Sora", role: "EXP/Jungle", type: "Fighter", tier: "S", proBan: false, banRate: 0,
    notes: "Most-banned hero in community ranked games last patch — extremely oppressive lane fighter.",
    counters: ["Poke mages", "Peel supports"],
    bait: null },
  { name: "Phoveus", role: "EXP", type: "Fighter", tier: "S", proBan: false, banRate: 0,
    notes: "Anti-mobility fighter, shreds dive/assassin-heavy comps.",
    counters: ["Ranged poke", "Kite marksmen"],
    bait: null },
  { name: "Fredrinn", role: "Jungle/EXP", type: "Fighter", tier: "S", proBan: false, banRate: 0,
    notes: "Sustain fighter that scales into an unkillable late-game duelist.",
    counters: ["Burst mages", "True damage"],
    bait: null },
  { name: "Zhuxin", role: "Mid", type: "Mage", tier: "S", proBan: false, banRate: 0,
    notes: "Highest pick rate in MPL ID S17 (63%+); zoning mage with strong wave clear and burst.",
    counters: ["Dive assassins (Lancelot, Helcurt)"],
    bait: null },
  { name: "Claude", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 9,
    notes: "Double-hero mechanic gives him elite DPS uptime; consistently the highest win-rate marksman in MPL ID.",
    counters: ["Silence/CC that locks down his passive partner"],
    bait: null },
  { name: "Kimmy", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 0,
    notes: "Hybrid magic marksman, strong laning phase and steady scaling.",
    counters: ["Dive assassins that close the gap fast"],
    bait: null },
  { name: "Granger", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 0,
    notes: "Reload-burst marksman, one of the highest single-target burst carries.",
    counters: ["Silence heroes", "Tanks with gap-close CC"],
    bait: null },
  { name: "Karrie", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 0,
    notes: "True-damage marksman, ideal into tank-heavy compositions.",
    counters: ["Burst assassins that kill her before she scales"],
    bait: null },
  { name: "Wanwan", role: "Gold", type: "Marksman", tier: "S", proBan: false, banRate: 0,
    notes: "High-mobility marksman, hard to pin down once she has movement items.",
    counters: ["Hard CC/root heroes (Khufra, Franco)"],
    bait: null },
  { name: "Angela", role: "Roam", type: "Support", tier: "S", proBan: false, banRate: 0,
    notes: "Attaches to a carry and doubles their kill threat — dangerous in coordinated 5-man play.",
    counters: ["Burst that one-shots the carry before Angela's shield/heal cycles"],
    bait: null },
  { name: "Floryn", role: "Roam", type: "Support", tier: "S", proBan: false, banRate: 0,
    notes: "Heal-based support, keeps fragile late-game cores alive through extended fights.",
    counters: ["Burst/true-damage assassins"],
    bait: null },
  { name: "Carmilla", role: "Roam", type: "Support", tier: "S", proBan: false, banRate: 0,
    notes: "Lifesteal-share support, strong in extended skirmishes and objective fights.",
    counters: ["Poke mages that punish grouping"],
    bait: null },
  { name: "Uranus", role: "EXP", type: "Tank", tier: "S", proBan: false, banRate: 0,
    notes: "Regeneration tank, nearly unkillable 1v1 in extended lane fights.",
    counters: ["True damage/percent-HP burst"],
    bait: null },
  { name: "Grock", role: "EXP", type: "Tank", tier: "S", proBan: false, banRate: 0,
    notes: "Wall-stun tank with strong early lane pressure and vision control.",
    counters: ["Ranged poke that punishes his wall cooldown"],
    bait: null },

  // ===== A TIER =====
  { name: "Selena", role: "Mid/Jungle", type: "Assassin/Mage", tier: "A", proBan: false, banRate: 35,
    notes: "Dual-form pick/burst hero, flexible into both poke and dive comps.",
    counters: ["Tanks with silence"], bait: null },
  { name: "Mathilda", role: "Roam", type: "Support", tier: "A", proBan: false, banRate: 39,
    notes: "Mobility-support hybrid, snowballs the jungle/roam duo hard in the current meta.",
    counters: ["Hard CC that punishes her dash timing"], bait: null },
  { name: "Eudora", role: "Mid", type: "Mage", tier: "A", proBan: true, banRate: 58,
    notes: "Instant hard-CC burst mage, top-3 banned on live ladder.",
    counters: ["Tanks with tenacity/CC-immunity windows"], bait: null },
  { name: "Barats", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 0,
    notes: "Drag-and-slam fighter, strong pick-off potential from fog of war.",
    counters: ["Ranged kite marksmen"], bait: null },
  { name: "Sun", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 37,
    notes: "Clone-split-push specialist, dangerous in late-game side-lane pressure.",
    counters: ["AoE clear mages that punish the clone wave"], bait: null },
  { name: "Hanabi", role: "Gold", type: "Marksman", tier: "A", proBan: false, banRate: 0,
    notes: "Late-game hyper-scaling marksman with strong shield uptime.",
    counters: ["Burst assassins before she spikes"], bait: null },
  { name: "Kaja", role: "Roam", type: "Fighter", tier: "A", proBan: false, banRate: 0,
    notes: "Single-target pick tank/fighter, ultimate isolates the priority target.",
    counters: ["Tenacity items", "Purify"], bait: null },
  { name: "Lolita", role: "Roam", type: "Support", tier: "A", proBan: false, banRate: 0,
    notes: "Shield-and-slow specialist, hard-counters dive/burst assassin comps.",
    counters: ["Poke mages that punish her low mobility"], bait: "A strong counter-ban if the enemy comp is snowballing an assassin/dive core (Fanny, Marcel, Harley) — banning her removes their answer." },
  { name: "Chip", role: "Mid", type: "Support/Mage", tier: "A", proBan: false, banRate: 0, notes: "Utility pick with map-wide presence in current pro drafts.", counters: [], bait: null },
  { name: "Arlott", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 0, notes: "Mobility duelist fighter, strong in pro EXP lane trades.", counters: ["Tanks with silence"], bait: null },
  { name: "Esmeralda", role: "EXP", type: "Mage/Tank", tier: "A", proBan: false, banRate: 0, notes: "Shield-tank hybrid, tough to burst down in skirmishes.", counters: ["True damage marksmen (Claude, Karrie)"], bait: null },
  { name: "Zetian", role: "Mid", type: "Mage", tier: "A", proBan: false, banRate: 0, notes: "Puppet-summon zoning mage, contests objective fights from range.", counters: ["Dive assassins that close distance fast"], bait: null },
  { name: "Harith", role: "Mid", type: "Mage", tier: "A", proBan: false, banRate: 46, notes: "Blink-mobility mage, strong roaming and pick potential.", counters: ["Silence/CC-lockdown heroes"], bait: null },
  { name: "Pharsa", role: "Mid", type: "Mage", tier: "A", proBan: false, banRate: 0, notes: "Long-range AoE poke mage, dominant siege pick.", counters: ["Dive assassins/tanks that close the gap"], bait: null },
  { name: "Yve", role: "Mid", type: "Mage", tier: "A", proBan: false, banRate: 0, notes: "Zone-control mage, strong contested pick this patch.", counters: ["Fast dive heroes"], bait: null },
  { name: "Leomord", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 0, notes: "Mount-based fighter, strong pick-off and split-push threat.", counters: ["Crowd control that interrupts remount"], bait: null },
  { name: "Lapu-Lapu", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 0, notes: "Dual-stance duelist, flexible offense/defense fighter.", counters: ["Poke mages"], bait: null },

  // ===== B TIER =====
  { name: "Moskov", role: "Gold", type: "Marksman", tier: "B", proBan: false, banRate: 0, notes: "Pierce-damage marksman, strong wave clear and poke.", counters: ["Hard engage tanks"], bait: null },
  { name: "Brody", role: "Gold", type: "Marksman", tier: "B", proBan: false, banRate: 0, notes: "Burst-lifesteal marksman, snowballs hard with an early lead.", counters: ["Peel supports", "CC chains"], bait: null },
  { name: "Vexana", role: "Mid", type: "Mage", tier: "B", proBan: false, banRate: 0, notes: "Zombie-summon zoning mage, situational teamfight pick.", counters: ["Dive assassins"], bait: null },
  { name: "Valentina", role: "Mid", type: "Mage", tier: "B", proBan: false, banRate: 0, notes: "Skill-copy mage, flexible counter-pick against enemy mages.", counters: ["Silence heroes"], bait: null },
  { name: "Lylia", role: "Mid", type: "Mage", tier: "B", proBan: false, banRate: 0, notes: "AoE burst mage, strong teamfight zoning.", counters: ["Dive assassins"], bait: null },
  { name: "Guinevere", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "Stance-based duelist, strong pick-off ultimate.", counters: ["Ranged kite"], bait: null },
  { name: "Chou", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "Kickback duelist, high-skill pick/peel threat.", counters: ["Tenacity items"], bait: null },
  { name: "Nolan", role: "Jungle", type: "Assassin", tier: "B", proBan: false, banRate: 0, notes: "Mobility assassin, snowballs the early jungle.", counters: ["Tanks with CC"], bait: null },
  { name: "Ling", role: "Jungle", type: "Assassin", tier: "B", proBan: false, banRate: 0, notes: "Bamboo-mobility assassin, elite backline dive.", counters: ["Crowd control that catches him mid-dash"], bait: null },
  { name: "Helcurt", role: "Jungle", type: "Assassin", tier: "B", proBan: false, banRate: 0, notes: "Stealth-silence assassin, punishes squishy backlines.", counters: ["Vision/detection heroes, tanky comps"], bait: null },
  { name: "Suyou", role: "Jungle", type: "Assassin/Fighter", tier: "B", proBan: false, banRate: 0, notes: "New-patch hybrid duelist, situational pro pick.", counters: [], bait: null },
  { name: "Zilong", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "Classic scaling fighter, strong split-push late.", counters: ["Poke mages, CC chains"], bait: null },
  { name: "Alice", role: "Mid", type: "Mage", tier: "B", proBan: false, banRate: 0, notes: "Lifesteal AoE mage, strong extended-fight sustain.", counters: ["Burst before she stacks lifesteal"], bait: null },
  { name: "Kadita", role: "Mid", type: "Assassin/Mage", tier: "B", proBan: false, banRate: 51, notes: "Burst assassin-mage, contested community ban.", counters: ["Tanks with silence"], bait: null },
  { name: "Minsitthar", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "Spear-pull initiator fighter, strong pick-off from EXP lane.", counters: ["Ranged kite"], bait: null },
  { name: "Thamuz", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 49, notes: "Sustain fighter, snowballs off tower damage.", counters: ["Burst mages"], bait: null },
  { name: "Yu Zhong", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 49, notes: "Dragon-form duelist, strong 1v1 sustain fighter.", counters: ["CC chains that interrupt ultimate"], bait: null },
  { name: "Karina", role: "Mid", type: "Assassin", tier: "B", proBan: false, banRate: 46, notes: "Magic-burst assassin, punishes low-magic-resist comps.", counters: ["Tanks with magic resist and CC"], bait: null },
  { name: "Hayabusa", role: "Jungle", type: "Assassin", tier: "B", proBan: false, banRate: 0, notes: "Shadow-clone assassin, high mechanical ceiling pick-off.", counters: ["Vision heroes, CC chains"], bait: null },
  { name: "Hanzo", role: "Jungle", type: "Assassin", tier: "B", proBan: true, banRate: 44, notes: "Soul-swap execute assassin, dangerous vs low-mobility carries.", counters: ["Tanks with escape/immunity"], bait: null },

  // ===== C / Situational (kept for search completeness) =====
  { name: "Layla", role: "Gold", type: "Marksman", tier: "C", proBan: false, banRate: 0, notes: "Beginner-friendly poke marksman, rarely seen in current pro meta.", counters: [], bait: null },
  { name: "Bruno", role: "Gold", type: "Marksman", tier: "C", proBan: false, banRate: 0, notes: "Classic curve-shot marksman, off-meta currently.", counters: [], bait: null },
  { name: "Clint", role: "Gold", type: "Marksman", tier: "C", proBan: false, banRate: 0, notes: "Double-shot marksman, situational poke pick.", counters: [], bait: null },
  { name: "Irithel", role: "Gold", type: "Marksman", tier: "B", proBan: false, banRate: 0, notes: "Ranged auto-attack marksman with mobility crossbow leap.", counters: [], bait: null },
  { name: "Beatrix", role: "Gold", type: "Marksman", tier: "B", proBan: false, banRate: 0, notes: "Multi-weapon marksman, flexible damage profile.", counters: [], bait: null },
  { name: "Obsidia", role: "Mid", type: "Mage", tier: "B", proBan: false, banRate: 0, notes: "New-patch mage, situational pro appearances.", counters: [], bait: null },
  { name: "Kalea", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "New-patch fighter, occasional pro pick.", counters: [], bait: null },
  { name: "Aldous", role: "Jungle", type: "Fighter", tier: "C", proBan: false, banRate: 0, notes: "Stack-scaling fighter, rare in pro play due to snowball dependency.", counters: [], bait: null },
  { name: "Franco", role: "Roam", type: "Tank", tier: "B", proBan: false, banRate: 0, notes: "Hook-initiator tank, strong pick-off from fog/bushes.", counters: [], bait: null },
  { name: "Johnson", role: "Roam", type: "Tank", tier: "C", proBan: false, banRate: 0, notes: "Transform-initiator tank, situational surprise-engage pick.", counters: [], bait: null },
  { name: "Hylos", role: "Roam", type: "Tank", tier: "B", proBan: false, banRate: 0, notes: "Thorn-armor tank, strong vs auto-attack-heavy comps.", counters: [], bait: null },
  { name: "Akai", role: "Roam", type: "Tank", tier: "C", proBan: false, banRate: 0, notes: "Spin-engage tank, rarely prioritized this patch.", counters: [], bait: null },
  { name: "Tigreal", role: "Roam", type: "Tank", tier: "C", proBan: false, banRate: 0, notes: "Classic AoE-stun initiator tank.", counters: [], bait: null },
  { name: "Diggie", role: "Roam", type: "Support", tier: "B", proBan: false, banRate: 0, notes: "Anti-CC support, strong pick vs heavy-engage comps.", counters: [], bait: "If the enemy opens their bans with Diggie, they're almost certainly planning a hard-CC setter composition — mirror that read into your own bans." },
  { name: "Silvanna", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 51, notes: "AoE knock-up fighter, strong teamfight initiation from EXP lane.", counters: [], bait: null },
  { name: "Terizla", role: "EXP", type: "Fighter", tier: "B", proBan: false, banRate: 0, notes: "Chain-CC fighter, strong anti-mobility answer.", counters: [], bait: null },
  { name: "Masha", role: "Jungle", type: "Fighter", tier: "A", proBan: false, banRate: 0, notes: "HP-scaling fighter, top-3 win rate on live ladder this patch.", counters: [], bait: null },
  { name: "Argus", role: "EXP", type: "Fighter", tier: "A", proBan: false, banRate: 0, notes: "Immortal-sustain fighter, strong late-game 1v1 duelist.", counters: [], bait: null },
];

// Convenience lookups
const HERO_BY_NAME = Object.fromEntries(HERO_DB.map(h => [h.name, h]));
const ROLES = ["EXP", "Jungle", "Mid", "Gold", "Roam"];
